language: go
os: linux
go:
- 1.14.x
env:
- GO111MODULE=on
script:
- "./.travis.gofmt.sh"
- go test -v ./...
- go test -bench=. -benchmem
before_deploy: make VERSION=$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: XgYOtVeoyOWDyqjUEbVmeb6+dH/4xhATzerbxO3p5bEUvaasgNBMkiS0vglJn/bhfuGW5xxwb7E5lj3nmNJOe99Ay97p+vvmYMLdvR5PHrYAzrromV+fB2v3GWjZjfCJzBRcNyNfwBecOt54suwt2ov8A/ec07Sia3v5Ny5EN5OrHU/U5dzicC9wAMEhAV38oj3p3hDdlGIVM3m/mkwq70V8LwqvQVJbUK0RJhWqxNYmzoe8Co2y+RM7obxHeGOCU3d2A0CwujRZwRXwx1CnG7vaMmHBSqAcmIk5Omy4C6zqJZb51MROKNvTiSqqUasTyNHhJHeyNaD5+HLe6noIkFCsE8Np7RURx7Q3A7AA+m97Oxs+oMQbPrMFujhSU0QVBNhLwUaX9iJ/1awaL52CwCpla8tFFz9lpEhhL0YinxhJRPexoNBTSXjVFV8nd7mRBf/M80uBLFcQgeXdpMtp41Kr2FwruUylzfXMoTkh5BUp5MDQ7lSCQwdwl75A3Th/tB5K/j7/HfwgrGwHYFsKyfrw1lkdzzupFIKenJJyi5BNDVgZ+DQ1f6T8zjh1ZGMZZbe8XtZQSIDT5TW81x3cvaO870q42FdtJb/a3zeAISTxKK11tsVNxtStADfDE1cKqMunzbm5eOWfJ4I5i0tf9VhPz2xyffkckOznTU/ADLU=
  file: bin/*
  file_glob: true
  skip_cleanup: true
  on:
    repo: chuenlungwang/go-logger
    tags: true
